language: csharp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://ppa.launchpad.net/maarten-fonville/protobuf/ubuntu trusty main'
    packages:
      - protobuf-compiler

before_install:
  - mkdir -p src/protobuf
  - protoc --csharp_out=src/protobuf --proto_path=proto/proto bluzelle.proto database.proto audit.proto