// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: bluzelle.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace bluzelle_cs {

  /// <summary>Holder for reflection information generated from bluzelle.proto</summary>
  public static partial class BluzelleReflection {

    #region Descriptor
    /// <summary>File descriptor for bluzelle.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BluzelleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5ibHV6ZWxsZS5wcm90bxoOZGF0YWJhc2UucHJvdG8ipgIKDGJ6bl9lbnZl",
            "bG9wZRIOCgZzZW5kZXIYASABKAkSEQoJc2lnbmF0dXJlGAIgASgMEhEKCXRp",
            "bWVzdGFtcBgDIAEoBBIWCgxkYXRhYmFzZV9tc2cYCiABKAxIABIfChVwYmZ0",
            "X2ludGVybmFsX3JlcXVlc3QYCyABKAxIABIbChFkYXRhYmFzZV9yZXNwb25z",
            "ZRgMIAEoDEgAEg4KBGpzb24YDSABKAxIABIPCgVhdWRpdBgOIAEoDEgAEg4K",
            "BHBiZnQYDyABKAxIABIZCg9wYmZ0X21lbWJlcnNoaXAYECABKAxIABIYCg5z",
            "dGF0dXNfcmVxdWVzdBgRIAEoDEgAEhkKD3N0YXR1c19yZXNwb25zZRgSIAEo",
            "DEgAQgkKB3BheWxvYWQiLQoHYnpuX21zZxIbCgJkYhgKIAEoCzINLmRhdGFi",
            "YXNlX21zZ0gAQgUKA21zZ0IOqgILYmx1emVsbGVfY3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::bluzelle_cs.DatabaseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::bluzelle_cs.bzn_envelope), global::bluzelle_cs.bzn_envelope.Parser, new[]{ "Sender", "Signature", "Timestamp", "DatabaseMsg", "PbftInternalRequest", "DatabaseResponse", "Json", "Audit", "Pbft", "PbftMembership", "StatusRequest", "StatusResponse" }, new[]{ "Payload" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::bluzelle_cs.bzn_msg), global::bluzelle_cs.bzn_msg.Parser, new[]{ "Db" }, new[]{ "Msg" }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class bzn_envelope : pb::IMessage<bzn_envelope> {
    private static readonly pb::MessageParser<bzn_envelope> _parser = new pb::MessageParser<bzn_envelope>(() => new bzn_envelope());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<bzn_envelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::bluzelle_cs.BluzelleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bzn_envelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bzn_envelope(bzn_envelope other) : this() {
      sender_ = other.sender_;
      signature_ = other.signature_;
      timestamp_ = other.timestamp_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.DatabaseMsg:
          DatabaseMsg = other.DatabaseMsg;
          break;
        case PayloadOneofCase.PbftInternalRequest:
          PbftInternalRequest = other.PbftInternalRequest;
          break;
        case PayloadOneofCase.DatabaseResponse:
          DatabaseResponse = other.DatabaseResponse;
          break;
        case PayloadOneofCase.Json:
          Json = other.Json;
          break;
        case PayloadOneofCase.Audit:
          Audit = other.Audit;
          break;
        case PayloadOneofCase.Pbft:
          Pbft = other.Pbft;
          break;
        case PayloadOneofCase.PbftMembership:
          PbftMembership = other.PbftMembership;
          break;
        case PayloadOneofCase.StatusRequest:
          StatusRequest = other.StatusRequest;
          break;
        case PayloadOneofCase.StatusResponse:
          StatusResponse = other.StatusResponse;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bzn_envelope Clone() {
      return new bzn_envelope(this);
    }

    /// <summary>Field number for the "sender" field.</summary>
    public const int SenderFieldNumber = 1;
    private string sender_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sender {
      get { return sender_; }
      set {
        sender_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "signature" field.</summary>
    public const int SignatureFieldNumber = 2;
    private pb::ByteString signature_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Signature {
      get { return signature_; }
      set {
        signature_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 3;
    private ulong timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "database_msg" field.</summary>
    public const int DatabaseMsgFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString DatabaseMsg {
      get { return payloadCase_ == PayloadOneofCase.DatabaseMsg ? (pb::ByteString) payload_ : pb::ByteString.Empty; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        payloadCase_ = PayloadOneofCase.DatabaseMsg;
      }
    }

    /// <summary>Field number for the "pbft_internal_request" field.</summary>
    public const int PbftInternalRequestFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString PbftInternalRequest {
      get { return payloadCase_ == PayloadOneofCase.PbftInternalRequest ? (pb::ByteString) payload_ : pb::ByteString.Empty; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        payloadCase_ = PayloadOneofCase.PbftInternalRequest;
      }
    }

    /// <summary>Field number for the "database_response" field.</summary>
    public const int DatabaseResponseFieldNumber = 12;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString DatabaseResponse {
      get { return payloadCase_ == PayloadOneofCase.DatabaseResponse ? (pb::ByteString) payload_ : pb::ByteString.Empty; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        payloadCase_ = PayloadOneofCase.DatabaseResponse;
      }
    }

    /// <summary>Field number for the "json" field.</summary>
    public const int JsonFieldNumber = 13;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Json {
      get { return payloadCase_ == PayloadOneofCase.Json ? (pb::ByteString) payload_ : pb::ByteString.Empty; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        payloadCase_ = PayloadOneofCase.Json;
      }
    }

    /// <summary>Field number for the "audit" field.</summary>
    public const int AuditFieldNumber = 14;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Audit {
      get { return payloadCase_ == PayloadOneofCase.Audit ? (pb::ByteString) payload_ : pb::ByteString.Empty; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        payloadCase_ = PayloadOneofCase.Audit;
      }
    }

    /// <summary>Field number for the "pbft" field.</summary>
    public const int PbftFieldNumber = 15;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Pbft {
      get { return payloadCase_ == PayloadOneofCase.Pbft ? (pb::ByteString) payload_ : pb::ByteString.Empty; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        payloadCase_ = PayloadOneofCase.Pbft;
      }
    }

    /// <summary>Field number for the "pbft_membership" field.</summary>
    public const int PbftMembershipFieldNumber = 16;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString PbftMembership {
      get { return payloadCase_ == PayloadOneofCase.PbftMembership ? (pb::ByteString) payload_ : pb::ByteString.Empty; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        payloadCase_ = PayloadOneofCase.PbftMembership;
      }
    }

    /// <summary>Field number for the "status_request" field.</summary>
    public const int StatusRequestFieldNumber = 17;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString StatusRequest {
      get { return payloadCase_ == PayloadOneofCase.StatusRequest ? (pb::ByteString) payload_ : pb::ByteString.Empty; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        payloadCase_ = PayloadOneofCase.StatusRequest;
      }
    }

    /// <summary>Field number for the "status_response" field.</summary>
    public const int StatusResponseFieldNumber = 18;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString StatusResponse {
      get { return payloadCase_ == PayloadOneofCase.StatusResponse ? (pb::ByteString) payload_ : pb::ByteString.Empty; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        payloadCase_ = PayloadOneofCase.StatusResponse;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      DatabaseMsg = 10,
      PbftInternalRequest = 11,
      DatabaseResponse = 12,
      Json = 13,
      Audit = 14,
      Pbft = 15,
      PbftMembership = 16,
      StatusRequest = 17,
      StatusResponse = 18,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as bzn_envelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(bzn_envelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sender != other.Sender) return false;
      if (Signature != other.Signature) return false;
      if (Timestamp != other.Timestamp) return false;
      if (DatabaseMsg != other.DatabaseMsg) return false;
      if (PbftInternalRequest != other.PbftInternalRequest) return false;
      if (DatabaseResponse != other.DatabaseResponse) return false;
      if (Json != other.Json) return false;
      if (Audit != other.Audit) return false;
      if (Pbft != other.Pbft) return false;
      if (PbftMembership != other.PbftMembership) return false;
      if (StatusRequest != other.StatusRequest) return false;
      if (StatusResponse != other.StatusResponse) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Sender.Length != 0) hash ^= Sender.GetHashCode();
      if (Signature.Length != 0) hash ^= Signature.GetHashCode();
      if (Timestamp != 0UL) hash ^= Timestamp.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.DatabaseMsg) hash ^= DatabaseMsg.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.PbftInternalRequest) hash ^= PbftInternalRequest.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.DatabaseResponse) hash ^= DatabaseResponse.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Json) hash ^= Json.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Audit) hash ^= Audit.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Pbft) hash ^= Pbft.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.PbftMembership) hash ^= PbftMembership.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.StatusRequest) hash ^= StatusRequest.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.StatusResponse) hash ^= StatusResponse.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Sender.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Sender);
      }
      if (Signature.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Signature);
      }
      if (Timestamp != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Timestamp);
      }
      if (payloadCase_ == PayloadOneofCase.DatabaseMsg) {
        output.WriteRawTag(82);
        output.WriteBytes(DatabaseMsg);
      }
      if (payloadCase_ == PayloadOneofCase.PbftInternalRequest) {
        output.WriteRawTag(90);
        output.WriteBytes(PbftInternalRequest);
      }
      if (payloadCase_ == PayloadOneofCase.DatabaseResponse) {
        output.WriteRawTag(98);
        output.WriteBytes(DatabaseResponse);
      }
      if (payloadCase_ == PayloadOneofCase.Json) {
        output.WriteRawTag(106);
        output.WriteBytes(Json);
      }
      if (payloadCase_ == PayloadOneofCase.Audit) {
        output.WriteRawTag(114);
        output.WriteBytes(Audit);
      }
      if (payloadCase_ == PayloadOneofCase.Pbft) {
        output.WriteRawTag(122);
        output.WriteBytes(Pbft);
      }
      if (payloadCase_ == PayloadOneofCase.PbftMembership) {
        output.WriteRawTag(130, 1);
        output.WriteBytes(PbftMembership);
      }
      if (payloadCase_ == PayloadOneofCase.StatusRequest) {
        output.WriteRawTag(138, 1);
        output.WriteBytes(StatusRequest);
      }
      if (payloadCase_ == PayloadOneofCase.StatusResponse) {
        output.WriteRawTag(146, 1);
        output.WriteBytes(StatusResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Sender.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sender);
      }
      if (Signature.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Signature);
      }
      if (Timestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Timestamp);
      }
      if (payloadCase_ == PayloadOneofCase.DatabaseMsg) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(DatabaseMsg);
      }
      if (payloadCase_ == PayloadOneofCase.PbftInternalRequest) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(PbftInternalRequest);
      }
      if (payloadCase_ == PayloadOneofCase.DatabaseResponse) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(DatabaseResponse);
      }
      if (payloadCase_ == PayloadOneofCase.Json) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Json);
      }
      if (payloadCase_ == PayloadOneofCase.Audit) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Audit);
      }
      if (payloadCase_ == PayloadOneofCase.Pbft) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Pbft);
      }
      if (payloadCase_ == PayloadOneofCase.PbftMembership) {
        size += 2 + pb::CodedOutputStream.ComputeBytesSize(PbftMembership);
      }
      if (payloadCase_ == PayloadOneofCase.StatusRequest) {
        size += 2 + pb::CodedOutputStream.ComputeBytesSize(StatusRequest);
      }
      if (payloadCase_ == PayloadOneofCase.StatusResponse) {
        size += 2 + pb::CodedOutputStream.ComputeBytesSize(StatusResponse);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(bzn_envelope other) {
      if (other == null) {
        return;
      }
      if (other.Sender.Length != 0) {
        Sender = other.Sender;
      }
      if (other.Signature.Length != 0) {
        Signature = other.Signature;
      }
      if (other.Timestamp != 0UL) {
        Timestamp = other.Timestamp;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.DatabaseMsg:
          DatabaseMsg = other.DatabaseMsg;
          break;
        case PayloadOneofCase.PbftInternalRequest:
          PbftInternalRequest = other.PbftInternalRequest;
          break;
        case PayloadOneofCase.DatabaseResponse:
          DatabaseResponse = other.DatabaseResponse;
          break;
        case PayloadOneofCase.Json:
          Json = other.Json;
          break;
        case PayloadOneofCase.Audit:
          Audit = other.Audit;
          break;
        case PayloadOneofCase.Pbft:
          Pbft = other.Pbft;
          break;
        case PayloadOneofCase.PbftMembership:
          PbftMembership = other.PbftMembership;
          break;
        case PayloadOneofCase.StatusRequest:
          StatusRequest = other.StatusRequest;
          break;
        case PayloadOneofCase.StatusResponse:
          StatusResponse = other.StatusResponse;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Sender = input.ReadString();
            break;
          }
          case 18: {
            Signature = input.ReadBytes();
            break;
          }
          case 24: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 82: {
            DatabaseMsg = input.ReadBytes();
            break;
          }
          case 90: {
            PbftInternalRequest = input.ReadBytes();
            break;
          }
          case 98: {
            DatabaseResponse = input.ReadBytes();
            break;
          }
          case 106: {
            Json = input.ReadBytes();
            break;
          }
          case 114: {
            Audit = input.ReadBytes();
            break;
          }
          case 122: {
            Pbft = input.ReadBytes();
            break;
          }
          case 130: {
            PbftMembership = input.ReadBytes();
            break;
          }
          case 138: {
            StatusRequest = input.ReadBytes();
            break;
          }
          case 146: {
            StatusResponse = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class bzn_msg : pb::IMessage<bzn_msg> {
    private static readonly pb::MessageParser<bzn_msg> _parser = new pb::MessageParser<bzn_msg>(() => new bzn_msg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<bzn_msg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::bluzelle_cs.BluzelleReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bzn_msg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bzn_msg(bzn_msg other) : this() {
      switch (other.MsgCase) {
        case MsgOneofCase.Db:
          Db = other.Db.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bzn_msg Clone() {
      return new bzn_msg(this);
    }

    /// <summary>Field number for the "db" field.</summary>
    public const int DbFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::bluzelle_cs.database_msg Db {
      get { return msgCase_ == MsgOneofCase.Db ? (global::bluzelle_cs.database_msg) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.Db;
      }
    }

    private object msg_;
    /// <summary>Enum of possible cases for the "msg" oneof.</summary>
    public enum MsgOneofCase {
      None = 0,
      Db = 10,
    }
    private MsgOneofCase msgCase_ = MsgOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgOneofCase MsgCase {
      get { return msgCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMsg() {
      msgCase_ = MsgOneofCase.None;
      msg_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as bzn_msg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(bzn_msg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Db, other.Db)) return false;
      if (MsgCase != other.MsgCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (msgCase_ == MsgOneofCase.Db) hash ^= Db.GetHashCode();
      hash ^= (int) msgCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (msgCase_ == MsgOneofCase.Db) {
        output.WriteRawTag(82);
        output.WriteMessage(Db);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (msgCase_ == MsgOneofCase.Db) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Db);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(bzn_msg other) {
      if (other == null) {
        return;
      }
      switch (other.MsgCase) {
        case MsgOneofCase.Db:
          if (Db == null) {
            Db = new global::bluzelle_cs.database_msg();
          }
          Db.MergeFrom(other.Db);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 82: {
            global::bluzelle_cs.database_msg subBuilder = new global::bluzelle_cs.database_msg();
            if (msgCase_ == MsgOneofCase.Db) {
              subBuilder.MergeFrom(Db);
            }
            input.ReadMessage(subBuilder);
            Db = subBuilder;
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
